### PR TITLE
elder staff doesn't work with melee hero FIX

### PR DESCRIPTION
**Pull request by MouJiaoZi**

### CODE REVIEW

**Comment by MouJiaoZi** [comment]
Fixed Elder Staff don't trigger when the owner is melee hero
Fixed JUGG's drag blade fury talent drags global. now it's 1.5x fury radius
Fixed server freezes when JUGG use passive's active hit a invisible or attack immue unit

**Comment by MouJiaoZi** [comment]
fixed infinite balde fury range
     with enough CDR will refresh fury buff, with increased range talent making a super range

**Comment by IamInnocentX3** [comment]
Super range is intended. Using Refresher benefits Jugg.

Elder staff does not grant melee heroes burn damage. The burn damage is based on the distance between caster and target.

Let's see how Cookies first do.

**Comment by IamInnocentX3** [comment]
For the image talent fix, it's legendary. Thank you.

**Comment by RodneyMcKay** [comment]
Seems good since jugg is super super strong atm, we might change it later if the nerf was needed elsewhere than on this anyway!

**Pull request merged**
